Repository sider/sider-docs, pull requests merged in 2020-06, with the labels that each got.

#434 [Cppcheck] Note for a json file containing the configuration of addons
  docs/tools/cplusplus/cppcheck.md
Labels: enhancement

#431 Support PMD CPD
  docs/getting-started/custom-configuration.md
  docs/index.md
  docs/tools/others/pmd-cpd.md
  website/sidebars.json
Labels: DO NOT MERGE, enhancement

#445 [PMD CPD] Analyze multiple languages by default
  docs/tools/others/pmd-cpd.md
Labels: enhancement

#453 Add --volume in "Configuring cron jobs"
  docs/enterprise/config.md
  docs/enterprise/installation.md
Labels: documentation
