Repository sider/sider-docs, pull requests merged in 2020-10, with the labels that each got.

#506 [cpplint] Provide Sider's recommended set of rules
  docs/getting-started/recommended-rules.md
  docs/index.md
  docs/tools/cplusplus/cpplint.md
  website/sidebars.json
Labels: enhancement

#510 yarn upgrade
  website/yarn.lock
  yarn.lock
Labels: dependencies

#511 Fix MySQL connection URL
  docs/enterprise/config.md
  docs/enterprise/examples/single-node-with-docker-compose.md
  docs/enterprise/installation.md
  docs/enterprise/mysql.md
Labels: enterprise
