Repository sider/sider-docs, pull requests merged in 2020-07, with the labels that each got.

#458 Fix RuboCop document links
  docs/tools/ruby/rubocop.md
Labels: bug

#469 Support Clang-Tidy
  docs/getting-started/custom-configuration.md
  docs/index.md
  docs/tools/cplusplus/clang-tidy.md
  website/sidebars.json
Labels: DO NOT MERGE, enhancement

#476 [Cppcheck] Support the option `-I`
  docs/getting-started/custom-configuration.md
  docs/tools/cplusplus/clang-tidy.md
  docs/tools/cplusplus/cppcheck.md
Labels: enhancement
