Repository sider/sider-docs, pull requests merged in 2021-07, with the labels that each got.

#629 Add document about Education pack
  docs/billing-and-plans.md
Labels: documentation

#630 Add code quality documentation
  docs/assets/code-quality/branch-list.jpg
  docs/assets/code-quality/file-viewer.jpg
  docs/assets/code-quality/files-tab.jpg
  docs/assets/code-quality/inspections-tab.jpg
  docs/assets/code-quality/issues-tab.jpg
  docs/assets/code-quality/sider-dashboard.jpg
  docs/getting-started/code-quality.md
  docs/index.md
  website/sidebars.json
Labels: documentation, help wanted

#634 Fix dead links
  README.md
  docs/custom-rules/goodcheck.md
Labels: bug

#638 Enterprise release — July 2021
  docs/enterprise/examples/single-node-with-docker-compose.md
  docs/enterprise/releases/202107.md
  docs/enterprise/releases/index.md
  website/sidebars.json
Labels: documentation, enterprise

#639 [News] 2021-07-20
  docs/news/2021.md
  docs/tools/javascript/eslint.md
  docs/tools/others/goodcheck.md
Labels: enhancement

#641 Fix `<img>` tags to make compatible with JSX
  docs/getting-started/intro-videos.md
Labels: refactoring

#644 Fix company name on footer
  website/siteConfig.js
Labels: bug

#648 Delete Dockerfile and docker-compose.yml
  Dockerfile
  docker-compose.yml
Labels: refactoring

#655 Fix code block syntax with file name
  docs/enterprise/installation.md
Labels: bug

#656 News/2021 07 28
  docs/news/2021.md
  docs/tools/others/secret-scan.md
Labels: documentation
