Repository sider/sider-docs, pull requests merged in 2021-09, with the labels that each got.

#682 Bump `@docusaurus/*` from 2.0.0-beta.5 to 2.0.0-beta.6
  package.json
  yarn.lock
Labels: dependencies

#683 Manage GitHub Actions updates via Dependabot
  .github/dependabot.yml
Labels: dependencies

#678 [Metrics] Filter out package directories from being analyzed by default
  docs/getting-started/custom-configuration.md
Labels: enhancement, documentation

#684 News: 2021-09-06
  docs/news/2021.md
  docs/tools/dockerfile/hadolint.md
  docs/tools/go/golangci-lint.md
  docs/tools/java/checkstyle.md
  docs/tools/java/pmd.md
  docs/tools/javascript/coffeelint.md
  docs/tools/kotlin/detekt.md
  docs/tools/others/pmd-cpd.md
  docs/tools/python/pylint.md
  docs/tools/ruby/rubocop.md
  docs/tools/ruby/slim-lint.md
Labels: documentation
